#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@phpkod[-1]
	add ucitrack phpkod
	set ucitrack.@phpkod[-1].init=phpkod
	commit ucitrack
EOF

/etc/init.d/php7-fpm disable && /etc/init.d/php7-fpm stop
rm -f /tmp/luci-indexcache
exit 0
